version: '3.8'

services:
  backend:
    image: oussamasj179/spring-pmt-backend:latest
    container_name: backend
    ports:
      - "8080:8080"



  frontend:
    build: .
    ports:
      - "4200:80"
 


